#!/usr/bin/env python3
"""Generate docs/navigation/FILE_INDEX.md.

This index is intentionally low-frequency and comprehensive:
- it keeps root AGENTS.md compact,
- but guarantees every repository file is discoverable when needed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable, List

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "navigation" / "FILE_INDEX.md"

EXCLUDED_TOP_DIRS = {
    ".git",
    ".venv",
    ".cache",
    ".lake",
    "artifacts",
    "__pycache__",
}
EXCLUDED_NAMES = {
    ".DS_Store",
}
EXCLUDED_SUFFIXES = {
    ".pyc",
    ".olean",
    ".ilean",
    ".o",
    ".c",
    ".zip",
}


def _is_excluded(rel: Path) -> bool:
    if not rel.parts:
        return True
    if any(p in EXCLUDED_TOP_DIRS for p in rel.parts):
        return True
    if rel.name in EXCLUDED_NAMES:
        return True
    if rel.suffix in EXCLUDED_SUFFIXES:
        return True
    return False


def collect_indexable_files(root: Path = ROOT) -> List[str]:
    out: List[str] = []
    stack: List[Path] = [root]
    while stack:
        cur = stack.pop()
        for p in sorted(cur.iterdir()):
            rel = p.relative_to(root)
            if p.is_dir():
                # Prune excluded trees early (critical for large local caches).
                if any(part in EXCLUDED_TOP_DIRS for part in rel.parts):
                    continue
                stack.append(p)
                continue
            if _is_excluded(rel):
                continue
            out.append(rel.as_posix())
    out.sort()
    return out


def render_file_index(paths: Iterable[str]) -> str:
    lines = []
    lines.append("# Repository File Index\n")
    lines.append(
        "> This file is deterministically generated by "
        "`./.venv/bin/python tools/docs/generate_file_index.py --write`.\n"
    )
    lines.append(
        "Use this index only when detailed file-level discovery is needed; "
        "do not preload it into normal prompts.\n"
    )
    lines.append("## Policy\n")
    lines.append("- Every new repository file must be indexable from root navigation.\n")
    lines.append("- If a file is added/moved/deleted, regenerate this file in the same change.\n")
    lines.append("\n## Indexed Files\n")
    for rel in paths:
        lines.append(f"- `{rel}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="Write docs/navigation/FILE_INDEX.md")
    ap.add_argument("--json", action="store_true", help="Print indexed file list as JSON")
    args = ap.parse_args()

    files = collect_indexable_files(ROOT)
    if args.json:
        print(json.dumps(files, indent=2))
        return 0

    text = render_file_index(files)
    if args.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text + "\n", encoding="utf-8")
        print(f"[file-index] wrote {OUT.relative_to(ROOT)} ({len(files)} files)")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
