"""LOOP runtime package (Wave-B M1 minimal surface)."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "AssuranceLevel": (".assurance", "AssuranceLevel"),
    "DynamicEntryViolation": (".graph_runtime", "DynamicEntryViolation"),
    "EXEC_ALLOWED": (".model", "EXEC_ALLOWED"),
    "ExecutionState": (".model", "ExecutionState"),
    "LoopErrorEnvelope": (".errors", "LoopErrorEnvelope"),
    "LoopException": (".errors", "LoopException"),
    "LoopGraphRuntime": (".graph_runtime", "LoopGraphRuntime"),
    "MaintainerLoopSession": (".maintainer", "MaintainerLoopSession"),
    "LoopResourceArbiter": (".resource_arbiter", "LoopResourceArbiter"),
    "LoopRuntime": (".runtime", "LoopRuntime"),
    "LoopStore": (".store", "LoopStore"),
    "ResourceClass": (".resource_arbiter", "ResourceClass"),
    "ResourceConflict": (".resource_arbiter", "ResourceConflict"),
    "RunKeyInput": (".run_key", "RunKeyInput"),
    "RuntimeBudgets": (".runtime", "RuntimeBudgets"),
    "assert_wave_execution_report": (".wave_gate", "assert_wave_execution_report"),
    "build_dynamic_recovery_bundle": (".presets", "build_dynamic_recovery_bundle"),
    "build_dynamic_recovery_graph": (".presets", "build_dynamic_recovery_graph"),
    "build_formalization_bundle": (".presets", "build_formalization_bundle"),
    "build_formalization_graph": (".presets", "build_formalization_graph"),
    "build_maintainer_change_bundle": (".presets", "build_maintainer_change_bundle"),
    "build_maintainer_change_graph": (".presets", "build_maintainer_change_graph"),
    "build_default_review_policy": (".user_preferences", "build_default_review_policy"),
    "build_default_tiered_review_policy": (".review_strategy", "build_default_tiered_review_policy"),
    "build_preference_record": (".user_preferences", "build_preference_record"),
    "build_task_bootstrap_bundle": (".presets", "build_task_bootstrap_bundle"),
    "build_task_bootstrap_graph": (".presets", "build_task_bootstrap_graph"),
    "collect_dirty_tree_snapshot": (".dirty_tree_gate", "collect_dirty_tree_snapshot"),
    "compute_run_key": (".run_key", "compute_run_key"),
    "compute_review_scope_fingerprint": (".review_runner", "compute_review_scope_fingerprint"),
    "build_pyramid_review_plan": (".review_strategy", "build_pyramid_review_plan"),
    "build_review_orchestration_bundle": (".review_orchestration", "build_review_orchestration_bundle"),
    "build_review_orchestration_graph": (".review_orchestration", "build_review_orchestration_graph"),
    "assert_review_reconciliation_ready": (".review_reconciliation", "assert_review_reconciliation_ready"),
    "evaluate_wave_completion_gate": (".assurance", "evaluate_wave_completion_gate"),
    "close_maintainer_session": (".maintainer", "close_maintainer_session"),
    "execute_recorded_graph": (".maintainer", "execute_recorded_graph"),
    "default_preference_artifact_path": (".user_preferences", "default_preference_artifact_path"),
    "load_canonical_review_result": (".review_canonical", "load_canonical_review_result"),
    "load_preference_record": (".user_preferences", "load_preference_record"),
    "loop": (".sdk", "loop"),
    "materialize_maintainer_session": (".maintainer", "materialize_maintainer_session"),
    "nested": (".sdk", "nested"),
    "normalize_assurance_level": (".assurance", "normalize_assurance_level"),
    "parallel": (".sdk", "parallel"),
    "merge_partition_scope_paths": (".review_strategy", "merge_partition_scope_paths"),
    "partition_review_scope_paths": (".review_strategy", "partition_review_scope_paths"),
    "record_maintainer_node_result": (".maintainer", "record_maintainer_node_result"),
    "require_execution_transition": (".model", "require_execution_transition"),
    "resolve_effective_preferences": (".user_preferences", "resolve_effective_preferences"),
    "resume": (".sdk", "resume"),
    "run": (".sdk", "run"),
    "run_dirty_tree_gate": (".dirty_tree_gate", "run_dirty_tree_gate"),
    "run_review_closure": (".review_runner", "run_review_closure"),
    "persist_review_reconciliation": (".review_reconciliation", "persist_review_reconciliation"),
    "reconcile_review_rounds": (".review_reconciliation", "reconcile_review_rounds"),
    "serial": (".sdk", "serial"),
    "summarize_review_history": (".review_history", "summarize_review_history"),
    "validate_dirty_tree_snapshot": (".dirty_tree_gate", "validate_dirty_tree_snapshot"),
    "validate_execution_trace": (".model", "validate_execution_trace"),
    "validate_wave_execution_report": (".wave_gate", "validate_wave_execution_report"),
    "write_preference_record": (".user_preferences", "write_preference_record"),
}


def __getattr__(name: str) -> Any:
    try:
        module_name, attr_name = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_EXPORTS))

__all__ = [
    "AssuranceLevel",
    "DynamicEntryViolation",
    "EXEC_ALLOWED",
    "ExecutionState",
    "build_dynamic_recovery_bundle",
    "build_dynamic_recovery_graph",
    "build_formalization_bundle",
    "build_formalization_graph",
    "build_maintainer_change_bundle",
    "build_maintainer_change_graph",
    "build_default_review_policy",
    "build_default_tiered_review_policy",
    "build_preference_record",
    "build_pyramid_review_plan",
    "build_task_bootstrap_bundle",
    "build_task_bootstrap_graph",
    "build_review_orchestration_bundle",
    "build_review_orchestration_graph",
    "assert_review_reconciliation_ready",
    "close_maintainer_session",
    "LoopErrorEnvelope",
    "LoopException",
    "LoopGraphRuntime",
    "MaintainerLoopSession",
    "merge_partition_scope_paths",
    "LoopResourceArbiter",
    "LoopStore",
    "LoopRuntime",
    "ResourceClass",
    "ResourceConflict",
    "RunKeyInput",
    "RuntimeBudgets",
    "compute_run_key",
    "compute_review_scope_fingerprint",
    "collect_dirty_tree_snapshot",
    "default_preference_artifact_path",
    "execute_recorded_graph",
    "evaluate_wave_completion_gate",
    "load_canonical_review_result",
    "load_preference_record",
    "loop",
    "materialize_maintainer_session",
    "nested",
    "normalize_assurance_level",
    "parallel",
    "partition_review_scope_paths",
    "persist_review_reconciliation",
    "record_maintainer_node_result",
    "reconcile_review_rounds",
    "resolve_effective_preferences",
    "resume",
    "run",
    "run_review_closure",
    "require_execution_transition",
    "serial",
    "summarize_review_history",
    "run_dirty_tree_gate",
    "assert_wave_execution_report",
    "validate_wave_execution_report",
    "validate_dirty_tree_snapshot",
    "validate_execution_trace",
    "write_preference_record",
]
