#!/usr/bin/env python3
"""Generate docs/testing/TEST_MATRIX.md from tests/manifest.json.

Deterministic generator: stable ordering, no timestamps.

Usage:
  ./.venv/bin/python tools/tests/generate_test_matrix.py           # print to stdout
  ./.venv/bin/python tools/tests/generate_test_matrix.py --write  # write docs/testing/TEST_MATRIX.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "tests" / "manifest.json"
OUT = ROOT / "docs" / "testing" / "TEST_MATRIX.md"


TIER_ORDER = {
    "core": 0,
    "nightly": 1,
    "soak": 2,
    # Legacy compatibility only (not selectable via tests/run.py).
    "smoke": 9,
}


def load_manifest() -> Dict[str, Any]:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    version = str(data.get("version"))
    if version not in {"2", "3"}:
        raise SystemExit(
            f"[test-matrix] Unsupported manifest version: {data.get('version')} (expected 2 or 3)"
        )
    if not isinstance(data.get("tests"), list):
        raise SystemExit("[test-matrix] manifest.tests must be a list")
    return data


def md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def _profile_of(test: Dict[str, Any]) -> str:
    # Canonical key: `profile`; keep legacy `tier` compatibility.
    profile = str(test.get("profile", "")).strip()
    if profile:
        return profile
    return str(test.get("tier", "")).strip()


def render(md_tests: List[Dict[str, Any]]) -> str:
    lines: List[str] = []
    lines.append("# Test Matrix\n")
    lines.append("> This file is deterministically generated by `./.venv/bin/python tools/tests/generate_test_matrix.py --write`.\n")
    lines.append("\n")
    lines.append("## How to run\n")
    lines.append("- Core: `./.venv/bin/python tests/run.py --profile core`\n")
    lines.append("- Nightly: `./.venv/bin/python tests/run.py --profile nightly`\n")
    lines.append("- Soak/Stress: `./.venv/bin/python tests/run.py --profile soak`\n")
    lines.append("\n")
    lines.append("Tiers are inclusive: higher tiers include lower ones.\n")
    lines.append("\n")

    tiers = ["core", "nightly", "soak"]
    for tier in tiers:
        subset = [t for t in md_tests if _profile_of(t) == tier]
        if not subset:
            continue
        lines.append(f"## Tier: {tier}\n")
        lines.append("| id | phase | area | runtime_budget_sec | goal | command |\n")
        lines.append("|---|---|---|---:|---|---|\n")
        for t in subset:
            phase = ",".join(t.get("phase", [])) if isinstance(t.get("phase"), list) else str(t.get("phase"))
            area = ",".join(t.get("area", [])) if isinstance(t.get("area"), list) else str(t.get("area"))
            goal = md_escape(str(t.get("goal", "")))
            script = t.get("script") or t.get("path")
            if not script:
                raise SystemExit(f"[test-matrix] Missing script/path for test: {t.get('id')}")
            cmd = md_escape(f"./.venv/bin/python {script}")
            lines.append(
                f"| `{t['id']}` | `{phase}` | `{area}` | {int(t.get('runtime_budget_sec', 0))} | {goal} | `{cmd}` |\n"
            )
        lines.append("\n")

    lines.append("## Change rules (mandatory)\n")
    lines.append("- Add/move/delete a test script ⇒ must update `tests/manifest.json` and regenerate this matrix.\n")
    lines.append("- PR gate checks that this matrix matches the registry (mismatch = fail).\n")
    lines.append("\n")
    return "".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="Write to docs/testing/TEST_MATRIX.md")
    args = ap.parse_args()

    data = load_manifest()
    tests: List[Dict[str, Any]] = list(data["tests"])

    # deterministic order: profile then id
    tests.sort(key=lambda t: (TIER_ORDER.get(_profile_of(t), 9), str(t.get("id"))))

    out = render(tests)

    if args.write:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(out, encoding="utf-8")
        print(f"[test-matrix] wrote {OUT.relative_to(ROOT)}")
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
