#!/usr/bin/env python3
"""Contract check: LOOP Wave-A contract docs completeness and key semantics."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

REQUIRED_DOCS = [
    ROOT / "docs" / "agents" / "PLANS.md",
    ROOT / "docs" / "contracts" / "LOOP_RUNTIME_CONTRACT.md",
    ROOT / "docs" / "contracts" / "LOOP_GRAPH_CONTRACT.md",
    ROOT / "docs" / "contracts" / "LOOP_RESOURCE_ARBITER_CONTRACT.md",
    ROOT / "docs" / "contracts" / "LOOP_AUDIT_CONTRACT.md",
    ROOT / "docs" / "contracts" / "LOOP_MCP_CONTRACT.md",
    ROOT / "docs" / "contracts" / "LOOP_PYTHON_SDK_CONTRACT.md",
    ROOT / "docs" / "contracts" / "LOOP_WAVE_EXECUTION_CONTRACT.md",
]

REQUIRED_SNIPPETS = {
    "docs/agents/PLANS.md": [
        "must use the stable execplan-addressable closeout alias",
        "must not cite a run-key-specific `GraphSummary.jsonl` path",
    ],
    "docs/contracts/LOOP_RUNTIME_CONTRACT.md": [
        "AI_REVIEW -> RUNNING",
        "`HUMAN_REVIEW` MUST NOT appear in execution track as a blocking state",
        "Assurance levels",
        "FAST",
        "LIGHT",
        "STRICT",
        "ai_review_prompt_ref",
        "ai_review_response_ref",
        "ai_review_summary_ref",
        "agent_provider_id",
        "instruction_scope_refs",
        "max_dynamic_recovery_rounds_per_exception = 2",
        "max_dynamic_recovery_total_minutes = 45",
        "PROMOTION_BLOCKED_BY_AUDIT",
        "graph-level `PARALLEL`/`NESTED` express composition semantics, not proof of concurrent execution by themselves",
        "true concurrent execution is controlled by `graph_spec.scheduler.max_parallel_branches`",
        "runtime MUST persist scheduler evidence",
        "runtime MUST persist nested lineage evidence",
        "host/workflow adapter concepts",
    ],
    "docs/contracts/LOOP_GRAPH_CONTRACT.md": [
        "STATIC_USER_MODE",
        "SYSTEM_EXCEPTION_MODE",
        "Dynamic graph entry is allowed only when",
        "GraphSummary.jsonl",
        "executed=true",
        "replay/backfill of legacy `GraphSummary.jsonl` rows",
        "graph payload MUST remain schema-valid",
        "host metadata sidecar",
        "allow_terminal_predecessors",
        "all-pass",
        "before implementation begins",
        "MaintainerSession.json",
        "NodeJournal.jsonl",
        "MaintainerProgress.json",
        "MaintainerCloseoutRef.json",
        "closeout_ref_ref",
        "session/progress/closeout-return surfaces should expose that alias as `closeout_ref_ref`",
        "session_created_at_utc",
        "session_created_at_epoch_ns",
        "older same-plan session must not overwrite a newer stable closeout ref alias",
        "stale execplan bytes",
        "must reject stale frozen inputs before rewriting the stable closeout ref alias",
        "legacy sessions missing `required_context_hash` or `instruction_chain_hash` must be rematerialized before closeout",
        "scope_observed_stamp",
        "mutate-and-restore scope drift after `ai_review_node`",
        "must not mask upstream `FAILED` or `TRIAGED` outcomes as `PASSED`",
        "worst upstream terminal class rather than the first lexicographic non-pass predecessor",
        "only valid on sink nodes with at least one incoming edge",
        "must not be attached to non-sink, `RACE`, or `QUORUM` nodes",
        "scheduler execution evidence",
        "nested lineage evidence",
        "`PARALLEL` and `NESTED` are graph semantics first",
        "`graph_spec.scheduler.max_parallel_branches` defines the upper bound for true concurrent execution",
        "lineage record for each nested target",
        "synthesized `UPSTREAM_BLOCKED` placeholders",
        "Maintainer bookkeeping `loop_closeout` is the explicit exception",
        "not by overloading free-form predecessor `reason_code` text",
    ],
    "docs/contracts/LOOP_RESOURCE_ARBITER_CONTRACT.md": [
        "IMMUTABLE",
        "APPEND_ONLY",
        "MUTABLE_CONTROLLED",
        "lease + CAS protocol is mandatory",
    ],
    "docs/contracts/LOOP_AUDIT_CONTRACT.md": [
        "AUDIT_FLAGGED",
        "S1_CRITICAL",
        "S2_MAJOR",
        "S3_MINOR",
        "non-blocking for already-finished execution path",
    ],
    "docs/contracts/LOOP_MCP_CONTRACT.md": [
        "loop/definitions/*",
        "loop/runs/*",
        "loop/graphs/*",
        "loop/components/*",
        "loop/resources/*",
        "loop/audit/*",
        "loop/providers/*",
        "loop/review-history/*",
        "idempotency_key",
        "instruction_scope_refs",
    ],
    "docs/contracts/LOOP_PYTHON_SDK_CONTRACT.md": [
        "loop(...)",
        "serial(...)",
        "parallel(...)",
        "run(...)",
        "resume(...)",
        "assurance_level",
        "FAST | LIGHT | STRICT",
        "agent_provider",
        "agent_profile",
        "review_history",
        "instruction_scope_refs",
        "resolved_invocation_signature",
        "error_code",
        "error_class",
        "retryable",
        "ExecPlan -> graph_spec -> test node -> implement node -> verify node -> AI review node -> LOOP closeout",
        "deterministic reviewer runner",
        "non-empty review scope file list",
        "visibility/context pack",
        "required_context_refs",
        "semantic-idle gate",
        "canonical review payload",
        "CanonicalReviewResult.schema.json",
        "raw provider stdout/stderr are audit evidence only",
        "mutate-and-restore scope rewrites",
        "materialize_maintainer_session",
        "MaintainerLoopSession",
        "build_default_review_policy(...)",
        "build_default_tiered_review_policy(...)",
        "`Budget Saver` is the committed default preset",
        "`FAST + low` is the default reviewer path",
        "`LOW_PLUS_MEDIUM` is the committed default reviewer tier policy",
        "`medium` is the standard bounded escalation tier",
        "`medium` is a bounded escalation for small-scope high-risk core logic",
        "`STRICT / xhigh` is exceptional",
        "`LOW_ONLY` staged-review policies MAY set `final_integrated_closeout.review_tier = LOW`",
        "`strategy_plan.closeout_policy.review_tier_policy = LOW_ONLY`",
        "Explicit exception plans MAY set `final_integrated_closeout.review_tier = STRICT`",
        "`strategy_plan.bounded_medium_profile` MUST be non-empty",
        "`final_integrated_closeout.agent_profile` MUST match `strategy_plan.bounded_medium_profile` exactly",
        "`strategy_plan.strict_exception_profile` MUST be non-empty in helper-authored/current strategies",
        "missing `strategy_plan.closeout_policy.review_tier_policy` is rejected on the default authoritative replay path",
        "`allow_historical_strategy_replay=True`",
        "Explicit historical replay mode MAY deterministically backfill `strategy_plan.strict_exception_profile` for supported legacy MEDIUM/STRICT-closeout plans that match one of the supported historical omit sets",
        "`final_integrated_closeout.agent_profile` MUST match `strategy_plan.strict_exception_profile` exactly",
        "partition_review_scope_paths(...)",
        "merge_partition_scope_paths(...)",
        "build_pyramid_review_plan(...)",
        "build_review_orchestration_graph(...)",
        "build_review_orchestration_bundle(...)",
        "planning aids only",
        "build_review_orchestration_graph(...)` compiles the schema-valid executable LOOP review graph payload only",
        "build_review_orchestration_bundle(...)` compiles the executable LOOP review graph plus deterministic sidecar routing metadata",
        "authoritative artifact for per-node reviewer-routing/audit metadata",
        "`graph_spec` may still persist coarse orchestration metadata",
        "authoritative source for per-node reviewer routing",
        "machine-readable `stage_manifest`",
        "containing one entry per executable orchestration node",
        "including non-review orchestration nodes such as `review_intake` and `finding_dedupe`",
        "join each entry back to `graph_spec.nodes` via its stable `node_id`",
        "`node_id`",
        "alias forms such as `foo.py` and `./foo.py` MUST be rejected as duplicates",
        "Reviewer-launching nodes MUST include `agent_profile`",
        "Non-review orchestration nodes that do not launch a reviewer MUST omit `agent_profile`",
        "Authoritative orchestration bundles MUST reject blank routing or scope metadata",
        "top-level `agent_provider_id`",
        "top-level `full_scope_fingerprint`",
        "top-level `effective_scope_fingerprint`",
        "any reviewer-launching stage `agent_profile`",
        "any partition `scope_fingerprint`",
        "`final_integrated_closeout.scope_fingerprint`",
        "MUST validate authoritative scope fingerprints against the live repository bytes under the supplied `repo_root`",
        "`strategy_plan.strategy_fingerprint` MUST match the canonical hash of the authoritative strategy-plan content that executable orchestration artifacts actually consume",
        "MUST cover the complete top-level provenance surface",
        "MUST NOT fork only because replayed plans mutate ignored metadata",
        "`strategy_plan.strategy_id` MUST remain `review.pyramid_partition.v1`",
        "`partition_review_scope_paths(...)`, `merge_partition_scope_paths(...)`, and `build_pyramid_review_plan(...)` are planning aids only",
        "deep follow-up stage is materialized via nested child-review nodes",
        "final integrated closeout sink is the only closeout-authoritative stage",
        "final integrated closeout sink MUST remain executable after post-dedupe advisory stages",
        "In explicit no-followup runs, `finding_dedupe` is still a hard gate",
        "When `deep_partition_followup.partition_ids=[]`, `effective_scope_paths` and `final_integrated_closeout.scope_paths` MUST match the frozen `fast_partition_scan.partition_ids` lineage exactly",
        "Fast partition scan nodes still gate `finding_dedupe`",
        "`fast_partition_scan.partition_ids` MUST preserve the canonical `strategy_plan.partitions` order exactly",
        "`strategy_plan.full_scope_paths` MUST preserve canonical repo-relative file order",
        "`strategy_plan.partitions` itself MUST preserve the canonical helper-derived partition order",
        "`strategy_plan.partitioning_policy` MUST preserve the helper-authored partitioning policy shape exactly",
        "`max_files_per_partition` MUST remain a positive integer policy field; string/bool lookalikes such as `\"2\"` or `true` are not authoritative replays",
        "`strategy_plan.partitions.*.scope_paths` MUST preserve canonical repo-relative file order within each partition",
        "`strategy_plan.stages` MUST preserve the canonical helper-authored stage order exactly",
        "helper-authored stage descriptor shape exactly",
        "`review_tier`, `finding_policy`, `selection_policy`, or `closeout_eligible`",
        "deep_partition_followup.partition_ids` MUST stay within the frozen `fast_partition_scan.partition_ids` subset",
        "unique `partition_id` values and non-empty `scope_paths`",
        "duplicate or unknown `stage_id` entries",
        "exact disjoint cover of `full_scope_paths`",
        "overlapping partition files",
        "repeated files inside a partition",
        "later stages can reflect real staged narrowing instead of forcing a full-scope re-review",
        "deep follow-up stage and the final integrated closeout stage MUST reflect that narrowed effective scope deterministically",
        "`strategy_plan.selected_partition_ids` MUST match `deep_partition_followup.partition_ids` exactly",
        "explicit `followup_partition_ids` are supplied to `build_pyramid_review_plan(...)`",
        "must not lexicographically reorder `part_100+` partition ids",
        "`strategy_plan.partitions[*].partition_id` numeric prefix MUST remain zero-padded",
        "`strategy_plan.partitions[*].partition_id` values MUST preserve the canonical helper-derived routing ids exactly",
        "`strategy_plan.partitions` MUST also match the helper-generated partition boundaries exactly for the declared `partitioning_policy`",
        "boundary-equivalent `max_files_per_partition` values are accepted when the frozen helper-generated partition boundaries remain identical",
        "MUST preserve the frozen `fast_partition_scan.partition_ids` order exactly",
        "deep_partition_followup.scope_paths` MUST stay within the selected partition lineage",
        "canonical selected partition lineage exactly",
        "deep_partition_followup.scope_paths`, `effective_scope_paths`, and `final_integrated_closeout.scope_paths` MUST match exactly",
        "exactness is sequence-sensitive, not set-sensitive",
        "`strategy_plan.effective_scope_source` MUST match `final_integrated_closeout.scope_source`",
        "MUST use a canonical helper-authored provenance label",
        "`FULL_SCOPE_AFTER_EMPTY_FOLLOWUP` is only valid when `deep_partition_followup.partition_ids=[]`",
        "the empty `effective_scope_paths=[]` input is shorthand for \"keep the canonical full fast-scan scope\"",
        "final_integrated_closeout.scope_paths` MUST also stay within that same selected partition lineage",
        "MUST NOT repeat the same repo file path more than once",
        "narrows inside a selected multi-file partition",
        "partition_scope_paths",
        "partition_scope_fingerprint",
        "scope_fingerprint_basis",
        "REPO_FILE_BYTES",
        "PATH_SET",
        "When `followup_partition_ids` is non-empty, replaying the helper-derived merged scope back into `build_pyramid_review_plan(...)` alongside the same `followup_partition_ids` MUST preserve the same provenance metadata and `strategy_fingerprint`",
        "composition_notes.fast_partition_node_ids",
        "`finding_dedupe` stage-manifest `scope_paths` / `scope_fingerprint` MUST freeze the actual `fast_partition_scan.partition_ids` lineage",
        "followup_partition_ids=[])` MUST be valid",
        "followup_partition_ids=[], effective_scope_paths=[])` MUST also be valid",
        "deep follow-up stage may have empty `partition_ids` / `scope_paths`",
        "final_integrated_closeout.scope_paths` MUST match `effective_scope_paths` exactly",
        "final_integrated_closeout.scope_fingerprint` MUST match `effective_scope_fingerprint`",
        "`strategy_plan.closeout_policy` MUST preserve the helper-authored closeout policy shape exactly",
        "`strategy_plan.closeout_policy.intermediate_rounds_are_advisory` and `strategy_plan.closeout_policy.requires_integrated_scope_closeout` MUST remain `true`",
        "must also reject stale fingerprint metadata",
        "must reject stale `strategy_fingerprint` values",
        "machine-readable reconciliation contract for the `finding_dedupe` stage",
        "stable `resource_id` locator for the reconciliation state",
        "`artifact_schema_ref = docs/schemas/ReviewSupersessionReconciliation.schema.json`",
        "`authoritative_closeout_stage_id = final_integrated_closeout`",
        "`late_output_disposition_enum = APPLIED | NOOP_ALREADY_COVERED | REJECTED_WITH_RATIONALE`",
        "`reconcile_review_rounds(...)`",
        "`assert_review_reconciliation_ready(...)`",
        "`persist_review_reconciliation(...)`",
        "`ReviewSupersessionReconciliation.schema.json`",
        "authoritative finding ledger",
        "outside any per-run `artifacts/loop_runtime/by_key/<run_key>/...` tree",
        "MaintainerProgress.json",
        "MaintainerCloseoutRef.json",
        "closeout_ref_ref",
        "`MaintainerSession.json`, `MaintainerProgress.json`, and `close_maintainer_session(...)` return summaries MUST expose `closeout_ref_ref`",
        "session_created_at_utc",
        "session_created_at_epoch_ns",
        "stale frozen inputs",
        "must reject stale execplan bytes before settled-state closeout",
        "legacy sessions missing `required_context_hash` or `instruction_chain_hash` must be rematerialized before closeout",
        "scope_observed_stamp",
        "mutate-and-restore scope drift after `ai_review_node`",
        "bookkeeping_pending_node_ids",
        "current_node_mode",
        "Maintainer `loop_closeout` remains a bookkeeping sink",
        "ordinary runnable work",
        "post-hoc `GraphSummary` alone is insufficient",
        "Legacy blocked-closeout replay compatibility is not limited to the summary row",
        "`GraphSummary.jsonl`, `NodeResults.json`, and `graph/arbitration.jsonl`",
        "observation_policy",
        "`execplan_ref` MUST stay disjoint from `scope_paths`",
        "freeze an incomplete chain",
        "required_context_refs` MUST stay disjoint from `scope_paths`",
        "canonicalize `instruction_scope_refs` to the active `AGENTS.md` chain",
        "run identity MUST include the frozen `graph_spec` contents",
        "`execplan_ref` as well as `scope_paths` and `required_context_refs`",
        "`serial(...)`, `parallel(...)`, and `nested(...)` are LOOP core composition helpers",
        "`OPERATOR`, `MAINTAINER`, and `worktree` policies are host/workflow adapters",
    ],
    "docs/contracts/LOOP_WAVE_EXECUTION_CONTRACT.md": [
        "Assurance level policy (FAST/LIGHT/STRICT)",
        "STRICT completion gate",
        "ai_review_prompt_ref",
        "ai_review_response_ref",
        "ai_review_summary_ref",
        "AI_REVIEW verdict enum: `PASS | REPAIRABLE | UNRESOLVED_BLOCKER | NON_RETRYABLE`",
        "REPAIRABLE and retry budget remains -> RUNNING",
        "REPAIRABLE and retry budget exhausted -> TRIAGED (`REVIEW_BUDGET_EXHAUSTED`)",
        "same finding_fingerprint repeats >= 2 -> TRIAGED (`REVIEW_STAGNATION`)",
        "`HUMAN_REVIEW` is asynchronous evidence and MUST NOT block the execution track",
        "agent_provider_id",
        "resolved_invocation",
        "instruction_scope_refs",
        "history_context_refs",
        "review_history_consistency",
        "contradiction_count",
        "DirtyTreeGate",
        "`dirty_tree` evidence must be present",
        "worktree must be clean before pass",
        "bounded execution (hard timeout + idle timeout)",
        "transport idle from semantic idle",
        "SEMANTIC_IDLE_TIMEOUT",
        "bounded extension (default cap: max 5 reconnect events)",
        "timed_out=true",
        "exit_code=124",
        "timeout_command_span",
        "REVIEW_UNRESOLVED_BLOCKER",
        "REVIEW_WALL_CLOCK_BUDGET_EXHAUSTED",
        "if `REVIEW_REPAIR_LOOP` occurs, terminal closure MUST come from a later AI review round",
        "reusing the same `prompt_ref` or `response_ref` across distinct AI review rounds is forbidden",
        "`codex exec review`",
        "ExecPlan -> graph_spec -> test node -> implement node -> verify node -> AI review node -> LOOP closeout",
        "manual closeout is exceptional only",
        "TRIAGED_TOOLING",
        "must still execute after `AI review` reaches `FAILED` or `TRIAGED`",
        "must not improve the terminal class decided by `AI review`",
        "review scope MUST be a non-empty file list",
        "CanonicalReviewResult",
        "raw provider capture and LOOP closeout MUST be separate stages",
        "response artifact MUST exist and be non-empty before `REVIEW_RUN`",
        "event.item.agent_message",
        "non-assistant `final_message` / `last_message` fallbacks are forbidden",
        "`LOW_PLUS_MEDIUM` is the committed default reviewer tier policy",
        "`FAST + low` remains the baseline reviewer path",
        "`medium` is the standard bounded escalation tier",
        "`LOW_ONLY` policies may still keep the integrated no-escalation closeout at `LOW`",
        "`STRICT / xhigh` remains exceptional",
        "review.prompt.baseline.v1",
        "review.prompt.exhaustive.v1",
        "LOOP_REVIEW_PROMPT_SHA256",
        "exhaustive reviewer protocol",
        "anti-dribble",
        "omission self-check",
        "controlled prompt experiment",
        "PROMPT_PROTOCOL_ONLY",
        "same frozen scope/context/provider settings",
        "authoritative staged review bundles MUST keep reviewer-launching stages on `review.prompt.exhaustive.v1`",
        "canonical prompt frozen inputs must match the run",
        "normalize line endings before exact prompt comparison",
        "persist `prompt_protocol_id` only for canonical prompts",
        "`declared_prompt_protocol_id`",
        "runner MAY require the exhaustive protocol before provider launch",
        "allow_legacy_prompt_protocol_backfill=True",
        "explicit exception review plans may still select a `STRICT / xhigh` final integrated closeout",
        "scope fingerprint mismatch makes the attempt stale",
        "scope observed stamp mismatch",
        "`artifacts/reviews/`",
        "visibility/context pack",
        "required_context_refs",
        "NO_TERMINAL_EVENT",
        "provider JSON event stream",
        "subjective early termination is forbidden",
        "minimum observation window for `codex_cli` is 600 seconds",
        "two-minute impatience aborts are invalid for `codex_cli`",
        "10-minute transport-idle default",
        "20-minute semantic-idle default",
        "explicit empty follow-up selection is allowed",
        "effective_scope_paths=[]",
        "must NOT erase the final integrated closeout review",
        "must preserve the same narrowing provenance and fingerprint as the original partition selection",
        "reject duplicate partition routing ids or empty partition scopes before executable review nodes are materialized",
        "alias forms such as `foo.py` and `./foo.py` still represent the same file",
        "partition-local intermediate rounds are not closeout-authoritative by themselves",
        "final `AI_REVIEW_CLOSEOUT` must come from a final integrated closeout review over the effective main scope after partition merge/dedupe",
        "deep-stage narrowed scope and the final integrated closeout scope must remain exactly aligned",
        "machine-readable `finding_dedupe` lineage record",
        "`CONFIRMED | DISMISSED | SUPERSEDED`",
        "`finding_key` MUST bind back to a stable source-finding identifier",
        "MUST NOT invent dedupe-local opaque keys",
        "`finding_key` MUST equal that `finding_id`",
        "`finding_key` MUST equal the stable advisory `finding_fingerprint`",
        "reconciliation record is required before the authoritative integrated closeout may claim that advisory findings were narrowed away or merged",
        "the final integrated closeout tier is `MEDIUM`",
        "the `finding_dedupe` reconciliation stage must freeze that narrowed fast-stage lineage",
        "staged narrowing is valuable even without real runtime concurrency",
        "review orchestration graphs may execute fast partition scans in parallel",
        "deep follow-up rounds may be materialized as nested child-review nodes",
        "final integrated closeout remains the only closeout-authoritative review stage",
        "final integrated closeout sink may run after post-dedupe advisory stages",
        "in explicit no-followup runs, `finding_dedupe` still remains a hard gate",
        "in explicit no-followup runs, the authoritative final integrated closeout scope must still match the frozen fast-stage lineage exactly",
        "fast partition scans still gate `finding_dedupe`",
        "authoritative reconciliation artifact",
        "Terminal closeout MUST consume that authoritative finding ledger",
        "`ReviewSupersessionReconciliation.schema.json`",
    ],
}


def _fail(msg: str) -> int:
    print(f"[loop-contract-docs][FAIL] {msg}", file=sys.stderr)
    return 2


def main() -> int:
    missing = [str(p.relative_to(ROOT)) for p in REQUIRED_DOCS if not p.exists()]
    if missing:
        print("[loop-contract-docs][FAIL] missing required docs:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        return 2

    for rel, snippets in REQUIRED_SNIPPETS.items():
        p = ROOT / rel
        text = p.read_text(encoding="utf-8")
        for s in snippets:
            if s not in text:
                return _fail(f"{rel} missing snippet `{s}`")

    print("[loop-contract-docs] OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
