#!/usr/bin/env python3
"""Deterministically rebuild AUTO_FROM_ANNOTATION reverse links from Lean annotations."""

from __future__ import annotations

import copy
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ANNOTATION_RE = re.compile(r"LEAN_LINK\s+claim_id=(\S+)\s+clause_id=(\S+)\s+span_id=(\S+)")
DECL_START_RE = re.compile(r"^\s*(theorem|lemma|def|abbrev|example|opaque|instance)\s+([A-Za-z_][A-Za-z0-9_']*)\b")


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def slugify(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", str(text).strip().lower()).strip("_") or "item"


def make_review(confidence: float = 0.95) -> dict[str, Any]:
    uncertainty = round(max(0.0, min(1.0, 1.0 - confidence)), 4)
    return {
        "state": "AUTO_EXTRACTED" if confidence >= 0.78 else "NEEDS_REVIEW",
        "confidence": round(confidence, 4),
        "uncertainty_score": uncertainty,
        "last_updated_utc": utc_now_iso(),
        "reviewer": None,
        "note": "auto-generated by tools.formalization.resync_reverse_links",
    }


def parse_declaration_starts(lines: list[str]) -> list[tuple[int, str]]:
    starts: list[tuple[int, str]] = []
    for index, line in enumerate(lines, start=1):
        match = DECL_START_RE.match(line)
        if match:
            starts.append((index, match.group(2)))
    return starts


def infer_declaration_for_line(*, line: int, declaration_starts: list[tuple[int, str]], prefer_after: bool = False) -> str:
    if not declaration_starts:
        return ""
    after = [name for start_line, name in declaration_starts if start_line >= line]
    if prefer_after and after:
        return after[0]
    for index, (start_line, name) in enumerate(declaration_starts):
        next_start = declaration_starts[index + 1][0] if index + 1 < len(declaration_starts) else 10**9
        if start_line <= line < next_start:
            return name
    if after:
        return after[0]
    before = [name for start_line, name in declaration_starts if start_line <= line]
    if before:
        return before[-1]
    return declaration_starts[-1][1]


def resync_annotation_reverse_links(
    *,
    ledger: dict[str, Any],
    annotation_files: list[Path],
) -> tuple[dict[str, Any], dict[str, Any]]:
    updated = copy.deepcopy(ledger)
    reverse_links = [link for link in updated.get("lean_reverse_links", []) if isinstance(link, dict)]
    keep = [link for link in reverse_links if link.get("link_origin") != "AUTO_FROM_ANNOTATION"]
    seen_ids = {str(link.get("reverse_link_id", "")) for link in keep}

    module_by_file: dict[str, str] = {}
    decl_by_file: dict[str, str] = {}
    for binding in updated.get("formalization_bindings", []):
        if not isinstance(binding, dict):
            continue
        lean_target = binding.get("lean_target", {})
        lean_target = lean_target if isinstance(lean_target, dict) else {}
        file_path = str(lean_target.get("file_path", ""))
        if file_path:
            module_by_file[file_path] = str(lean_target.get("module", "UNKNOWN"))
            decl_by_file[file_path] = str(lean_target.get("declaration_name", ""))

    rebuilt = list(keep)
    for path in annotation_files:
        resolved = path.expanduser()
        if not resolved.exists() or resolved.suffix != ".lean":
            continue
        lines = resolved.read_text(encoding="utf-8").splitlines()
        declaration_starts = parse_declaration_starts(lines)
        for line_no, line in enumerate(lines, start=1):
            match = ANNOTATION_RE.search(line)
            if not match:
                continue
            claim_id, clause_id, span_id = match.groups()
            reverse_link_id = f"{slugify(resolved.as_posix())}.ann.{slugify(clause_id)}.{line_no}"
            if reverse_link_id in seen_ids:
                continue
            seen_ids.add(reverse_link_id)
            rebuilt.append(
                {
                    "reverse_link_id": reverse_link_id,
                    "link_origin": "AUTO_FROM_ANNOTATION",
                    "lean_ref": {
                        "module": module_by_file.get(str(resolved), "UNKNOWN"),
                        "file_path": str(resolved),
                        "declaration_name": infer_declaration_for_line(
                            line=line_no,
                            declaration_starts=declaration_starts,
                        )
                        or decl_by_file.get(str(resolved), ""),
                        "line": line_no,
                        "column": 1,
                    },
                    "target": {
                        "claim_id": claim_id,
                        "clause_id": clause_id,
                        "span_id": span_id,
                    },
                    "review": make_review(0.95),
                    "notes": "parsed from LEAN_LINK annotation in .lean file",
                }
            )

    updated["lean_reverse_links"] = rebuilt
    report = {
        "generated_at_utc": utc_now_iso(),
        "annotation_file_count": len(annotation_files),
        "reverse_links_total": len(rebuilt),
        "annotation_links": sum(1 for link in rebuilt if link.get("link_origin") == "AUTO_FROM_ANNOTATION"),
    }
    return updated, report
