#!/usr/bin/env python3
"""Deterministic skill stub + coverage generator (Phase5 platform).

Goal (platform-only): ensure *every capability command* has at least one skill manual.

This tool does NOT write business semantics.
It only:
- detects uncovered commands from tools/capabilities/phase{3,4,5}.yaml
- proposes (and optionally applies) minimal stub files so Codex has something to load

By default it prints a plan (no writes). Use --apply to write.

Generated files live under:
- .agents/skills/<skill-name>/SKILL.md
- .agents/skills/<skill-name>/references/coverage.yaml

Agent Skills spec requires:
- YAML frontmatter with name + description in SKILL.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import yaml


def canonical_json(obj: Any) -> str:
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def load_manifest_commands(repo_root: Path) -> Dict[str, str]:
    """Return {command_id: phase}."""
    out: Dict[str, str] = {}
    for phase_file in ("phase3.yaml", "phase4.yaml", "phase5.yaml"):
        p = repo_root / "tools" / "capabilities" / phase_file
        if not p.exists():
            continue
        data = yaml.safe_load(p.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            continue
        phase = data.get("phase")
        if not isinstance(phase, str) or not phase:
            continue
        cmds = data.get("commands")
        if not isinstance(cmds, list):
            continue
        for c in cmds:
            if not isinstance(c, dict):
                continue
            cid = c.get("id")
            if isinstance(cid, str) and cid:
                out[cid] = phase
    return out


def load_skill_coverage(repo_root: Path) -> Dict[str, List[str]]:
    """Return {skill_name: covers_commands[]}"""
    base = repo_root / ".agents" / "skills"
    out: Dict[str, List[str]] = {}
    if not base.exists():
        return out

    for sdir in sorted([p for p in base.iterdir() if p.is_dir()], key=lambda p: p.name):
        skill_name = sdir.name
        cov = sdir / "references" / "coverage.yaml"
        if not cov.exists():
            out[skill_name] = []
            continue
        data = yaml.safe_load(cov.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            out[skill_name] = []
            continue
        cmds = data.get("covers_commands")
        if isinstance(cmds, list):
            out[skill_name] = sorted(set([str(x).strip() for x in cmds if str(x).strip()]))
        else:
            out[skill_name] = []
    return out


DEFAULT_ASSIGNMENTS: Dict[str, List[Tuple[str, str]]] = {
    # (command_id_prefix, skill_name)
    "phase3": [
        ("gc.", "leanatlas-gc"),
        ("dedup.", "leanatlas-dedup"),
        ("promotion.", "leanatlas-promote"),
        ("promote.", "leanatlas-promote"),
    ],
    "phase4": [
        ("msc.", "leanatlas-domain-mcp"),
        ("mcp.", "leanatlas-domain-mcp"),
    ],
    "phase5": [
        ("automation.", "leanatlas-automations"),
        ("bench.", "leanatlas-automations"),
        ("skills.", "leanatlas-automations"),
    ],
}


def assign_skill(phase: str, command_id: str) -> Optional[str]:
    for prefix, sk in DEFAULT_ASSIGNMENTS.get(phase, []):
        if command_id.startswith(prefix):
            return sk
    return None


def skill_stub_markdown(skill_name: str) -> str:
    return (
        "---\n"
        f"name: {skill_name}\n"
        "description: Placeholder skill stub generated by Phase5 (platform). The owning phase must fill in the real instructions and references.\n"
        "---\n\n"
        f"> owner: TODO\n\n"
        "TODO: Fill this skill with step-by-step instructions, examples, and links to the relevant contracts/schemas.\n"
    )


def coverage_yaml(covers: List[str]) -> str:
    lines = [
        'version: "0.1"',
        "covers_commands:",
    ]
    for cid in sorted(set(covers)):
        lines.append(f"  - {cid}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--out", default=None, help="Write plan JSON to this path (else stdout)")
    ap.add_argument("--apply", action="store_true", help="Apply the plan (write files)")
    args = ap.parse_args()

    repo_root = Path(args.repo_root).resolve()

    commands = load_manifest_commands(repo_root)
    coverage = load_skill_coverage(repo_root)

    covered: Set[str] = set()
    for cmds in coverage.values():
        for c in cmds:
            covered.add(c)

    uncovered = sorted([cid for cid in commands.keys() if cid not in covered])

    actions: List[Dict[str, Any]] = []
    updates: Dict[str, Set[str]] = {}
    creates: Set[str] = set()
    unassigned: List[str] = []

    for cid in uncovered:
        phase = commands.get(cid, "")
        sk = assign_skill(phase, cid) if phase else None
        if sk is None:
            unassigned.append(cid)
            continue
        updates.setdefault(sk, set()).add(cid)

        sdir = repo_root / ".agents" / "skills" / sk
        if not sdir.exists():
            creates.add(sk)

    for sk in sorted(creates):
        actions.append(
            {
                "type": "create_skill_dir",
                "skill": sk,
                "paths": {
                    "skill_md": f".agents/skills/{sk}/SKILL.md",
                    "coverage_yaml": f".agents/skills/{sk}/references/coverage.yaml",
                },
            }
        )

    for sk in sorted(updates.keys()):
        actions.append(
            {
                "type": "update_coverage",
                "skill": sk,
                "add_commands": sorted(updates[sk]),
                "coverage_yaml": f".agents/skills/{sk}/references/coverage.yaml",
            }
        )

    plan = {
        "schema": "leanatlas.skills_stubgen.plan",
        "schema_version": "0.1.0",
        "repo_root": str(repo_root),
        "counts": {
            "commands": len(commands),
            "skills": len(coverage),
            "uncovered_commands": len(uncovered),
            "unassigned": len(unassigned),
            "actions": len(actions),
        },
        "uncovered_commands": uncovered,
        "unassigned_commands": unassigned,
        "actions": actions,
    }

    plan_txt = canonical_json(plan)

    if args.out:
        out_path = Path(args.out)
        if not out_path.is_absolute():
            out_path = repo_root / out_path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(plan_txt, encoding="utf-8")
        print(f"[skills_stubgen] wrote plan {out_path.relative_to(repo_root)}")
    else:
        print(plan_txt, end="")

    if not args.apply:
        return 0

    # Apply actions (deterministic; minimal writes).
    for sk in sorted(creates):
        sdir = repo_root / ".agents" / "skills" / sk
        (sdir / "references").mkdir(parents=True, exist_ok=True)
        (sdir / "SKILL.md").write_text(skill_stub_markdown(sk), encoding="utf-8")
        (sdir / "references" / "coverage.yaml").write_text(coverage_yaml(list(updates.get(sk, set()))), encoding="utf-8")

    for sk, add in sorted(updates.items(), key=lambda kv: kv[0]):
        sdir = repo_root / ".agents" / "skills" / sk
        cov = sdir / "references" / "coverage.yaml"
        existing: List[str] = []
        if cov.exists():
            try:
                data = yaml.safe_load(cov.read_text(encoding="utf-8"))
                if isinstance(data, dict) and isinstance(data.get("covers_commands"), list):
                    existing = [str(x).strip() for x in data.get("covers_commands") if str(x).strip()]
            except Exception:
                existing = []
        merged = sorted(set(existing) | set(add))
        cov.parent.mkdir(parents=True, exist_ok=True)
        cov.write_text(coverage_yaml(merged), encoding="utf-8")

    print(f"[skills_stubgen] applied plan (actions={len(actions)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
